### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'token_type_ids'

### ISSUE THREAD

**Issue by Wepdekr** [Anni-Zou/Decker#6]
Traceback:
Traceback (most recent call last):
  File "/root/autodl-tmp/Decker-main/run_confact.py", line 408, in <module>
    main()
  File "/root/autodl-tmp/Decker-main/run_confact.py", line 324, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint, ignore_keys_for_eval=["my_metrics"])
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/transformers/trainer.py", line 1400, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/transformers/trainer.py", line 1984, in training_step
    loss = self.compute_loss(model, inputs)
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/transformers/trainer.py", line 2016, in compute_loss
    outputs = model(**inputs)
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'token_type_ids'

**Comment by Wepdekr** [comment]
@Anni-Zou
